project:
  type: website
  output-dir: docs

website:
  title: "Eivory Ortiz's Website"
  site-path: "/warmup-eivory-ortiz/"
  reader-mode: true
  repo-url: https://github.com/eivoryortiz/personal-eivory-ortiz
  repo-actions: issue
  navbar:
    tools: 
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/index.qmd
        text: Articles 
      - href: posts/index.qmd
        text: Blog


  sidebar:

    - id: none
      style: "docked"
      background: light
      logo: images/bia-w-a-PO8Woh4YBD8-unsplash.jpg
      collapse-level: 2
      contents: 
        - section: "Articles"
          href: articles/index.qmd
          contents: 
            - text: "Solution to Everything"
              href:  articles/article_01.qmd
            - text: "Solution to Flattening"
              href:  articles/article_02.qmd 
            - text: "Major Enhancement"
              href: articles/article_03.qmd
        - section: "Posts"
          href: posts/index.qmd
          contents: "posts/*/*.qmd"
          sort:
            - "date desc"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

execute: 
  freeze: true

