---
title: "Why Being Yourself Is In Fact Challenging"
---

No matter where you go and what you do it seems as if being yourself is a taunting thing to be. No one prepares you for the consequences and really the reality of the world when you are actually yourself. What it means to be yourself is something many have asked and many wonder today what or how we should go about approaching this question.

Although for me I can say currently it is easy for me to be myself, who knows if I will be able to say that much less type that when I am 50. I and others are constantly changing and because of this we really don't know exactly how we are going to be portrayed or remember later on in life. Causing many to become stressed over this issue. Because who really knows what being yourself actually means.

There are many things in this world that shape our perception of time and our perception of the things around this. This has room to cause for others to say  whether or not it made you who you are today. I would argue that it is important to note that learning is involved in the process to being yourself. This can range from the phrases people say about "mind, heart, soul" or something along the lines of "I am me because of GOD".

All of which are valid, but still the question remains about why it is difficult to be yourself. There are versions of yourself past and present and of course future. What you say and do can be reflective of the current you or a past you or a future you. But you should not be always held in the status of being untouchable or immoral or God like. It's simply not achievable nor should it be. Many people give people this idea that they have to be perfect. When in reality being perfect is impossible.

Someone can say that cheesy line of the word impossible means im possible but that simply isn't true, do humans have wings? No. So why would you say to someone it isn't impossible when you know for a fact that humans can't have wings? This is the same rhetoric that goes on when you tell someone they can be themselves but you are holding them to standard. Or you are projectingg yourself onto them. This is also bad.

Because you are not giving the person the living breathing option to be themselves but rather you are trying to either macro or micro control them on how they should be themselves. If everyone was truly their most authentic selves this world would be different. But because of much unresolved issues people are dealing with regarding unrealisitic expectations. Many will never be truly themselves.

One could argue that I am on a high horse right now with what I have mentioned. There is room for that statement, but rest assure that just as there is room for that there is room for mine as well and all that fall along the spectrum of this discussion. Why? Because no human shares the same experience regardless if there is similarities to this life. It is still uniquely yours and what you choose to do or say with the free will is entirely up to you. Or it could be determined by circumstances or by others, the list goes on. But ultimately you have right to get to know you.

You have the undeniable right to live, and to live also implies to be yourself, and although this topic is so vast and complex I hope to whoever reads this at least knows that being yourself will never hurt you in comparison to all the benefits you'll get from it helping you!