---
title: "Lyrics To Songs"
---

Lyrics are something that fascinate and always have been.

I don't think I would like music if it weren't for lyrics. At least part of it.
This is why I think people should study more lyrics and really consider the evolution of words in music.

Because for a long period of time there weren't words in music and by that I mean songs. So this is why it is relatively new in concept.
And therefore should be looked more into. I would even comment that it is important that we appreciate lyrics more now than ever. As it seems that we are advancing more into the age of AI. The usage of creativity in all areas is starting to become a part of the reason for AI's usage. Whether this would be on social media or to the usage of song writing.

Lyrics can help convey the song just the same way someone would read a poem or a book that they are wanting to get a meaning out of. People write in journals to let go or express their feelings, lyrics can encompass all of this with music. I wish more people knew how people feel about lyrics.

Mainly in the sense that when people dedicate others songs majority of the time it is because of the lyrics, but if you have a background in music theory than of course you are going to go above and beyond when it comes to recommedning and even dedicating songs. Especially if lyrics are involved because you are understand that they too shape music.

It is due to this that I want more people to invest in lyric history, I was fortunate enough to get a class in my time in college regarding the history of music taught by Professor Powell and it really helped broadened but as well shap my appreciation for music but as well lyrics. How people can express themselves is so fascinating and especially in regards to writing albums. Because you're not just writing one song you are writing multiple. And even songs that just have one word but that word lyric matter to the art of the song help revolutionize music genres too!

Lyrics can make or break for some people what songs they listen too but nevertheless I think it is important to realize that there is value in understanding the art of lyrics. What words mean and what exactly can music do for you and what it can do to others. There is so much information out there regarding music and I do not think we as a society will ever stop producing music, but as a suggestion to those that have read up until now this brief article, I would suggest to start researching lyrics and why it shaped the evolution of music today as we know it.